/**
 * Floating numbers — the Pixi half. Phase-07.7c, ADR-017 §4.
 *
 * Draws the pool from `floating-number-state.ts` as pooled per-digit sprites.
 *
 * NO `Text`, DELIBERATELY. Pixi rasterises a texture per distinct string, so
 * "+12" and "+13" would be two GPU allocations — per frame, on the most
 * frequent effect in the game. Instead every glyph is one of eleven textures
 * generated by `scripts/generate-glyph-art.mjs`, and a number is composed from
 * pre-allocated digit sprites that are repositioned and retinted rather than
 * created. Nothing here allocates after construction.
 *
 * The glyphs are painted Parchment and TINTED here, so a coin number and an
 * item number cost the same eleven textures between them.
 */

import { Container, Sprite, type Texture } from 'pixi.js';

import { TILE_SIZE, WORLD_WIDTH } from '../../shared/constants';

import { bindAnimationLease, type AnimationLease } from './animation-lease';
import type { DirtyGate } from './dirty-gate';
import {
  FloatingKind,
  type FloatingNumberPool,
  type FloatingNumberView,
} from './floating-number-state';

/** Glyph metrics, from the generator: a 5×7 core in a 7×9 canvas. */
const GLYPH_WIDTH = 7;
/** Overlap by the outline column so digits read as one number, not a queue. */
const GLYPH_ADVANCE = GLYPH_WIDTH - 1;

/** How far a number rises over its life, in pixels. */
const RISE_PX = TILE_SIZE * 0.75;

/**
 * Digit sprites held ready.
 *
 * Capacity × 5 covers "+9999" on every number in the pool at once, which is
 * far past what the economy produces in a tick; beyond it, extra digits are
 * simply not drawn rather than allocated.
 */
const DIGITS_PER_NUMBER = 5;

/** Tint per kind. Reward Gold is the currency accent (STYLE_LOCK.md R-09). */
const KIND_TINT: Readonly<Record<FloatingKind, number>> = {
  [FloatingKind.Coins]: 0xf2c24c,
  [FloatingKind.Item]: 0xe8e0d4,
  [FloatingKind.Xp]: 0xa5d97e,
};

export interface FloatingNumberRenderer {
  /** Draws the pool at `nowMs`, and holds a lease only while it has content. */
  update(nowMs: number): void;
  destroy(): void;
}

export interface FloatingNumberRendererOptions {
  readonly layer: Container;
  readonly pool: FloatingNumberPool;
  readonly textureFor: (spriteKey: string) => Texture;
  readonly gate: DirtyGate;
}

/** Manifest key for one character of a formatted number. */
function glyphKey(character: string): string {
  return character === '+' ? 'ui-world:glyph_plus' : `ui-world:glyph_${character}`;
}

export function createFloatingNumberRenderer(
  options: FloatingNumberRendererOptions,
): FloatingNumberRenderer {
  const { layer, pool, textureFor, gate } = options;

  const root = new Container();
  layer.addChild(root);

  // Every sprite this renderer will ever use, made once.
  const sprites: Sprite[] = Array.from({ length: pool.capacity * DIGITS_PER_NUMBER }, () => {
    const sprite = new Sprite();
    sprite.visible = false;
    root.addChild(sprite);
    return sprite;
  });

  const lease: AnimationLease = bindAnimationLease(gate);

  /** Lays one number out from `next`, returning the cursor after it. */
  const drawNumber = (view: FloatingNumberView, next: number): number => {
    const row = Math.floor(view.tile / WORLD_WIDTH);
    const column = view.tile - row * WORLD_WIDTH;

    const text = view.text.slice(0, DIGITS_PER_NUMBER);
    const width = text.length * GLYPH_ADVANCE;

    // Centred on the tile, drifted so simultaneous numbers stay readable, and
    // rising as it fades.
    const originX = (column + 0.5) * TILE_SIZE - width / 2 + view.driftX * TILE_SIZE;
    const originY = row * TILE_SIZE - view.progress * RISE_PX;
    // Hold full opacity for the first half, then fade — a number that starts
    // fading immediately is unreadable at the moment it matters most.
    const alpha = view.progress < 0.5 ? 1 : 1 - (view.progress - 0.5) * 2;

    let cursor = next;
    for (let i = 0; i < text.length; i += 1) {
      const sprite = sprites[cursor];
      if (sprite === undefined) break; // pool exhausted: draw fewer, allocate none

      sprite.texture = textureFor(glyphKey(text[i] ?? ''));
      sprite.x = originX + i * GLYPH_ADVANCE;
      sprite.y = originY;
      sprite.tint = KIND_TINT[view.kind];
      sprite.alpha = alpha;
      // Above everything on its row; the number is the point, briefly.
      sprite.zIndex = row + 1;
      sprite.visible = true;
      cursor += 1;
    }
    return cursor;
  };

  return {
    update(nowMs) {
      const active = pool.activeAt(nowMs);
      lease.sync(active.length > 0);

      let cursor = 0;
      for (const view of active) cursor = drawNumber(view, cursor);

      // Everything the pass did not use is hidden rather than destroyed.
      for (let i = cursor; i < sprites.length; i += 1) {
        const sprite = sprites[i];
        if (sprite === undefined || !sprite.visible) break;
        sprite.visible = false;
      }
    },

    destroy() {
      // Before the layer that parents them goes; a lease outliving its view is
      // a permanent frame cost on the next scene (ADR-001 §2).
      lease.release();
      pool.clear();
      root.destroy({ children: true });
    },
  };
}
