/**
 * The quest chains as content. Phase-22 — ADR-034 §4, §5.
 *
 * What the data must hold: ids unique, thresholds strictly increasing so the
 * watermark can only walk forward, rewards positive and below the smallest
 * contract premium a step's own deliveries would have earned — quests season
 * the contract loop, never replace it.
 */

import { describe, expect, it } from 'vitest';

import { QUEST_CHAINS } from './quests';
import { RESIDENTS } from './residents';

describe('the chains', () => {
  it('every chain id is unique and namespaced', () => {
    const ids = QUEST_CHAINS.map((chain) => chain.id);
    expect(new Set(ids).size).toBe(ids.length);
    for (const id of ids) expect(id.startsWith('core:quest_')).toBe(true);
  });

  it('thresholds rise strictly, so the watermark can only walk forward', () => {
    for (const chain of QUEST_CHAINS) {
      expect(chain.steps.length).toBeGreaterThan(0);
      for (let i = 1; i < chain.steps.length; i += 1) {
        expect(chain.steps[i]!.threshold).toBeGreaterThan(chain.steps[i - 1]!.threshold);
      }
    }
  });

  it('rewards are positive integers, sized below contract money (ADR-034 §5)', () => {
    for (const chain of QUEST_CHAINS) {
      for (const step of chain.steps) {
        expect(Number.isInteger(step.rewardCoins)).toBe(true);
        expect(step.rewardCoins).toBeGreaterThan(0);
        expect(step.rewardCoins).toBeLessThanOrEqual(400);
        expect(step.objective.length).toBeGreaterThan(0);
      }
    }
  });

  it('every villager has a chain, and every requester is a real resident', () => {
    // THIS USED TO ASSERT `requesterChains.length === RESIDENTS.length`, which
    // was true while every resident had exactly one chain and the chains were
    // generated by `RESIDENTS.map()`. Phase-58 gave each of them a second,
    // authored chain (ADR-046 R-06), and the equality broke on content that is
    // strictly more of what the test wants.
    //
    // The two properties it was really protecting are below, and neither cares
    // how many chains a resident has: nobody is left out, and nobody is
    // invented.
    const residentIds = new Set<string>(RESIDENTS.map((resident) => resident.id));
    const requesterChains = QUEST_CHAINS.filter((chain) => chain.counter.kind === 'requester');

    const covered = new Set<string>();
    for (const chain of requesterChains) {
      if (chain.counter.kind === 'requester') {
        expect(
          residentIds.has(chain.counter.requester),
          `${String(chain.id)} is addressed to ${String(chain.counter.requester)}, who does not live here`,
        ).toBe(true);
        covered.add(String(chain.counter.requester));
      }
    }

    for (const resident of RESIDENTS) {
      expect(
        covered.has(String(resident.id)),
        `${String(resident.id)} has no quest chain — a villager with nothing to ask for is scenery`,
      ).toBe(true);
    }
  });
});
